repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args: ['--extra-keys=metadata.kernelspec metadata.language_info']
  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        additional_dependencies:
          - toml
          - numpy
          - matplotlib
          - scipy
          - rasterio
          - shapely
          - geopandas
          - clarabel
        exclude: |
          (?x)^(
            tests/|
            docs/
          )
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=pyproject.toml",
            "src/topotoolbox"
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
